### ISSUE TITLE
[BUG?] It is not possible to use more than one GPU for training on Kaggle

### ISSUE THREAD

**Issue by shirounanashi** [blaisewf/rvc-cli#52]
**Describe the bug**
When i try to use 2 GPUs on Kaggle, this error occours:
`[W socket.cpp:663] [c10d] The client socket has failed to connect to [localhost]:55292 (errno: 99 - Cannot assign requested address).`

**To Reproduce**
1. Simply put "0-1" in --gpu in training part on Kaggle

**Expected behavior**
Be able to use two GPUs for training.

**Assets**
![image](https://github.com/blaise-tk/RVC_CLI/assets/154093422/c460ab68-aa28-4c82-90ee-1316323ec163)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: chrome

**Additional context**
Yes, I was using the 2x T4, and was using the last commit ("fix multi gpu")

**Comment by TheTrustedComputer** [comment]
I also have a similar issue but with 2x 8GB AMD Radeon 5500 XTs in a local Docker container.

**Comment by shirounanashi** [comment]
I tested it, and this problem extends to Applio, and doesn't happen on the RVC mainline

**Comment by TheTrustedComputer** [comment]
@shirounanashi

I don't think it's a container issue. As you mentioned, I ran mainline RVC inside Docker, and multi-GPU training worked there. I believe the problem of parallel training not functioning has been around in Applio for a while. Not everyone has two or more GPUs for machine learning purposes. In fact, @blaisewf is already aware of this but doesn't have additional cards to test other than going to the cloud.

**Comment by shirounanashi** [comment]
I get it @TheTrustedComputer , I think I was wrong then, and Indeed, not everyone has multiple GPUs, I don't have it myself haha And I think it's impossible to discover the problem just through kaggle

**Comment by Vidalnt** [comment]
I don't think it's an applio bug, I tried to train with rvc-mainline with a very long dataset, which only allowed me to have a batch size of 7, when I wanted to test the two gpu's of the kaggle, then I got the error of insufficient vram. 
-- Bad Traductor

**Comment by TheTrustedComputer** [comment]
Using one GPU with 8 GB of VRAM, I can train with a batch size of 8 in mainline regardless of the dataset size. However, two GPUs require reducing it to 4, or I'll get out-of-memory errors. Whereas in Applio/RVC_CLI, training doesn't even start with 2+ GPUs.

**Comment by blaisewf** [comment]
Fixed
