### ISSUE TITLE
Feature request: expose RVC (applio) functionality through python package 

### ISSUE THREAD

**Issue by JackismyShephard** [blaisewf/rvc-cli#72]
I have for some point been using outdated RVC code for my song cover generation app and was considering integrating some of the newer additions to Applio. Then I discovered this project which is just great.  What would make it even greater is if  the newest RVC code from Applio was also exposed through a python package. Is that something that might happen in the near future?

**Comment by blaisewf** [comment]
we synchronize cli code with applio frequently

**Comment by blaisewf** [comment]
https://github.com/blaisewf/rvc-cli/commit/e5b8d9ab82983e57c13f6087ef9b2c374a66aa99
