### ISSUE TITLE
[Q/A] IndexError: tuple index out of range

### ISSUE THREAD

**Issue by ytoaa** [blaisewf/rvc-cli#76]
env\python.exe rvc_cli.py preprocess --model_name "johnnyc" --dataset_path "raw" --sample_rate "40000" --cpu_cores 4
env\python.exe rvc_cli.py extract --model_name "johnnyc" --rvc_version "v2" --sample_rate "40000" --gpu 0 --cpu_cores 4 --f0_method "rmvpe"
env\python.exe rvc_cli.py train --model_name "johnnyc" --rvc_version "v2" --save_every_epoch "3" --sample_rate "40000" --total_epoch 39
env\python.exe rvc_cli.py infer --input_path "C:\Users\gas\Documents\AIproject-sub\diff-svc\raw\bb.wav" --output_path "C:\Users\gas\Documents\AIproject-sub\rvc-cli\logs\johnnyc\output" --pth_path "C:\Users\gas\Documents\AIproject-sub\rvc-cli\logs\johnnyc\johnnyc_39e_7020s.pth" --index_path "C:\Users\gas\Documents\AIproject-sub\rvc-cli\logs\johnnyc\added_johnnyc_v2.index" --f0_method "rmvpe" --pitch 0

C:\Users\gas\Documents\AIproject-sub\rvc-cli>env\python.exe rvc_cli.py infer --input_path "C:\Users\gas\Documents\AIproject-sub\diff-svc\raw\bb.wav" --output_path "C:\Users\gas\Documents\AIproject-sub\rvc-cli\logs\johnnyc\output" --pth_path "C:\Users\gas\Documents\AIproject-sub\rvc-cli\logs\johnnyc\johnnyc_39e_7020s.pth" --index_path "C:\Users\gas\Documents\AIproject-sub\rvc-cli\logs\johnnyc\added_johnnyc_v2.index" --f0_method "rmvpe" --pitch 0
C:\Users\gas\Documents\AIproject-sub\rvc-cli\env\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
An error occurred during execution: tuple index out of range
Traceback (most recent call last):
  File "C:\Users\gas\Documents\AIproject-sub\rvc-cli\rvc_cli.py", line 1544, in main
    run_infer_script(
  File "C:\Users\gas\Documents\AIproject-sub\rvc-cli\rvc_cli.py", line 91, in run_infer_script
    "reverb_room_size": sliders[0],
IndexError: tuple index out of range

I couldn't really try to deduce. Can you help me?

**Comment by blaisewf** [comment]
ill update it soon with a fix

**Comment by ytoaa** [comment]
> ill update it soon with a fix

Is it a question of reasoning or learning?
Should we proceed with learning again after modifying the code?

**Comment by blaisewf** [comment]
pushed an update

**Comment by ytoaa** [comment]
> pushed an update

The same error still occurs after the update.

**Comment by blaisewf** [comment]
🫨

**Comment by ytoaa** [comment]
> 🫨

That was my mistake. Now I can deduce it properly! Thank you
